### ISSUE TITLE
Feet sliding in Talos simulation 

### ISSUE THREAD

**Issue by edantec** [loco-3d/crocoddyl#605] opened 2019-11-22 16:01 UTC
[Talos_reduced.py.zip](https://github.com/loco-3d/crocoddyl/files/3880278/Talos_reduced.py.zip)

Hello,

I don't know if it's a bug or feature, but I got a problem with sliding feet when trying to simulate a movement in which Talos stands still while reaching a target with its left hand. In this problem the feet should not be moving, but they end up  interpenetrating each other.

I use the DDP method to solve an optimisation problem with various weights (state and control regularization, goal tracking, CoM tracking). Contacts are enabled through 6D contact models. Joints limits are enabled through activation bounds. 

I have provided the simulation file I used. I'm using Python 2.7.

**Comment by cmastalli** [comment] 2019-11-22 16:12
It seems your are having numerical integration errors. This is expected in any DAE, not a bug, and note that the contact dynamics is a DAE.

To mitigate this numerical issue, you should increase the proportional -- Baumgarte  -- gain in your contact models (line 74 and 77 of your code).

For more details about these gains you might want to read the Crocoddyl paper: https://cmastalli.github.io/publications/crocoddyl20unpub.pdf

Yours,
Carlos

**Comment by cmastalli** [comment] 2019-11-22 16:12
Please let me know if this solves your problem.

**Comment by cmastalli** [comment] 2019-11-22 16:45
It seems you are using incorrectly the Baumgarte stabilization (i.e. contact gains in line 74 and 77), so it is expected to see sliding motions. Note that the reference placement is the origin of the inertial frame (i.e. world frame). So you have to options:
 1. Do not use proportional gain (zero value)
 2. Define the properly the reference placement, desired placement of the contact

I suggest to follow 1 because, typically, there is good numerical stability with only the damping term.

For more details about these gains you might want to read the Crocoddyl paper: https://cmastalli.github.io/publications/crocoddyl20unpub.pdf

Yours,
Carlos

**Comment by cmastalli** [comment] 2019-11-22 16:47
I will close this issue since it is expected behavior.

Feel free to reopen it, if it is needed for you

**Closed by cmastalli** 2019-11-22 16:47 UTC
